<h1 align="center"> Visualiza√ß√£o de Dados com Python</h1

<div style="display: flex; align-items: center;">
    <div style="flex: 1;">
        <table>
            <thead>
                <tr>
                    <th><strong>Termo [em ingl√™s]</strong></th>
                    <th><strong>Tradu√ß√£o</strong></th>
                    <th><strong>Observa√ß√µes</strong></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Chart</td>
                    <td>Gr√°fico</td>
                    <td>Geralmente √© acompanhado do tipo do gr√°fico. <br>Ex: Pie Chart (Pizza), Bar Chart (Barras), Line Chart (Linhas), Bubble Chart (Bolhas), etc.<br></td>
                </tr>
                <tr>
                    <td>Plot</td>
                    <td>Plotagem</td>
                    <td>Produ√ß√£o de uma imagem por meio de desenhos e linhas. A√ß√£o de construir o gr√°fico.</td>
                </tr>
                <tr>
                    <td>Axis / Axes</td>
                    <td>Eixo</td>
                    <td>Eixo dos gr√°ficos. <br>Ideia an√°loga √† Matem√°tica, na qual temos X e Y para o caso 2D e X, Y, Z para o caso 3D.<br></td>
                </tr>
                <tr>
                    <td>Label</td>
                    <td>R√≥tulo</td>
                    <td>S√£o os r√≥tulos que d√£o o nome e acompanham cada eixo. <br>Geralmente aparecem acompanhados do respectivo eixo. Ex: <code>x_label</code>, <code>y_label</code>, etc.<br></td>
                </tr>
                <tr>
                    <td>Grid</td>
                    <td>Grade/Malha</td>
                    <td>√â a estrutura de fundo de um gr√°fico. <br>Linhas horizontais e verticais espa√ßadas que servem de refer√™ncia para as unidades dos eixos.<br></td>
                </tr>
                <tr>
                    <td>Legend</td>
                    <td>Legenda</td>
                    <td>Caixa de texto descritivo, contendo informa√ß√µes sobre os elementos do gr√°fico. <br>Geralmente traz informa√ß√£o sobre o que significa determinada cor ou tra√ßado e/ou quais as vari√°veis sendo plotadas.<br></td>
                </tr>
            </tbody>
        </table>
    </div>
    <div style="flex: 1; text-align: center;">
        <img src="https://www.alura.com.br/artigos/assets/data-visualization-conhecendo-bibliotecas-python/img2_anatomia_de_uma_figura_matplotlib.jpeg" width="90%">
    </div>
</div>

*Refer√™ncias üìö*
1. https://matplotlib.org/stable/plot_types/
2. https://matplotlib.org/stable/gallery/
3. https://seaborn.pydata.org/examples/index.html
4. https://www.alura.com.br/artigos/o-que-e-um-histograma
5. https://www.alura.com.br/artigos/o-que-e-um-histograma

Estudo de caso:  
> Ao longo das aulas, vamos desenvolver um projeto para que essa empresa possa otimizar esses servi√ßos de aconselhamento e consultoria para essas pessoas que desejam fazer imigra√ß√£o.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('imigrantes_canada.csv')
df

,Pa√≠s,Continente,Regi√£o,1980,1981,1982,1983,1984,1985,1986,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
0,Afeganist√£o,√Åsia,Sul da √Åsia,16,39,39,47,71,340,496,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,58639
1,Alb√¢nia,Europa,Sul da Europa,1,0,0,0,0,0,1,...,1223,856,702,560,716,561,539,620,603,15699
2,Arg√©lia,√Åfrica,Norte da √Åfrica,80,67,71,69,63,44,69,...,3626,4807,3623,4005,5393,4752,4325,3774,4331,69439
3,Samoa Americana,Oce√¢nia,Polin√©sia,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,6
4,Andorra,Europa,Sul da Europa,0,0,0,0,0,0,2,...,0,1,1,0,0,0,0,1,1,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Vietn√£,√Åsia,Sudeste Asi√°tico,1191,1829,2162,3404,7583,5907,2741,...,1852,3153,2574,1784,2171,1942,1723,1731,2112,97146
191,Saara Ocidental,√Åfrica,Norte da √Åfrica,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,2
192,I√©men,√Åsia,√Åsia Ocidental,1,2,1,6,0,18,7,...,161,140,122,133,128,211,160,174,217,2985
193,Z√¢mbia,√Åfrica,√Åfrica Oriental,11,17,11,7,16,9,15,...,91,77,71,64,60,102,69,46,59,1677
194,Zimb√°bue,√Åfrica,√Åfrica Oriental,72,114,102,44,32,29,43,...,615,454,663,611,508,494,434,437,407,8598

<h2 align="center">An√°lise de tend√™ncias de migra√ß√£o do Brasil em um determinado per√≠odo </h2>

In [3]:
# Tornar o index do dataframe como o pa√≠s
df.set_index('Pa√≠s', inplace=True)
df.head(10)

,Continente,Regi√£o,1980,1981,1982,1983,1984,1985,1986,1987,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
Pa√≠s,,,,,,,,,,,,,,,,,,,,,
Afeganist√£o,√Åsia,Sul da √Åsia,16,39,39,47,71,340,496,741,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,58639
Alb√¢nia,Europa,Sul da Europa,1,0,0,0,0,0,1,2,...,1223,856,702,560,716,561,539,620,603,15699
Arg√©lia,√Åfrica,Norte da √Åfrica,80,67,71,69,63,44,69,132,...,3626,4807,3623,4005,5393,4752,4325,3774,4331,69439
Samoa Americana,Oce√¢nia,Polin√©sia,0,1,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,6
Andorra,Europa,Sul da Europa,0,0,0,0,0,0,2,0,...,0,1,1,0,0,0,0,1,1,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Vietn√£,√Åsia,Sudeste Asi√°tico,1191,1829,2162,3404,7583,5907,2741,1406,...,1852,3153,2574,1784,2171,1942,1723,1731,2112,97146
Saara Ocidental,√Åfrica,Norte da √Åfrica,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,2
I√©men,√Åsia,√Åsia Ocidental,1,2,1,6,0,18,7,12,...,161,140,122,133,128,211,160,174,217,2985
Z√¢mbia,√Åfrica,√Åfrica Oriental,11,17,11,7,16,9,15,23,...,91,77,71,64,60,102,69,46,59,1677
Zimb√°bue,√Åfrica,√Åfrica Oriental,72,114,102,44,32,29,43,68,...,615,454,663,611,508,494,434,437,407,8598